version: '3.8'
services:
  s4-app:
    container_name: s4_app
    restart: always
    env_file: .env
    image: odort/s4:v1.0.2
    build: .
    networks:
      - db_network
      - web_network
    ports:
      - 80:5005
    # depends_on:
    #   - postgres
  # nginx:
  #   container_name: nginx
  #   restart: always
  #   image: "nginx:latest"
  #   ports:
  #     - "85:85"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   networks:
  #     - web_network
  #   depends_on:
  #     - s4-app
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=mysecretpassword
  #     - POSTGRES_DB=s4-flask
  #     - POSTGRES_USER=s4-flask-user
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - db_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 